name             'windows_server'
maintainer       'Todd Pigram'
maintainer_email 'todd@toddpigram.com'
license          'Apache 2.0'
description      'Installs/Configures windows_server'
long_description 'Installs/Configures windows_server'
version          '0.5.3'
depends          'windows'
depends          'powershell'
depends          'boxstarter'
depends          'chocolatey'
